{
  try {
    out.close();
  }
 catch (  IOException e) {
    hasErrors=true;
  }
}
